version: "3.7"

services:
  web:
      container_name: frontend
      build:
        context: ./frontend
      ports:
        - 3000:3000

  api:
      container_name: backend
      build: 
        context: ./backend
      ports:
        - 8000:8000
